version: 0.2

phases:
  install:
    commands:
      - echo installing Nginx
      - sudo yum install nginx -y
  build:
    commands:
      - echo Build start
      - sudo cp index.html /var/www/html
  post_build:
    commands:
      - echo configuring Nginx server

artifacts:
  files:
    - /var/www/html/index.html
